### ISSUE TITLE
If send_email: False

### ISSUE THREAD

**Issue by ANemcov** [utmcrow/lostfilm-rss-parser#1]
"send_email: False", but I have error about "from: ***_"
'yaml.scanner.ScannerError: while scanning an alias
  in "config.yml", line 12, column 9
expected alphabetic or numeric character, but found '_'
  in "config.yml", line 12, column 10'

**Comment by v00g100skr** [comment]
can i see your full config?
or try to set something instead of ***\* (its not be used because email notification disabled, but parcer need data) 
or try to replace ***\* to '****'

**Comment by v00g100skr** [comment]
i have actual data in this place in my local config

**Comment by v00g100skr** [comment]
i replace lost data in config. 
its must working now

**Comment by ANemcov** [comment]
it's nice workaround :)
