### ISSUE TITLE
Список новых торрентов в письме

### ISSUE THREAD

**Issue by martrix78** [utmcrow/lostfilm-rss-parser#2]
Добрый день.
Новые торренты в email оповещении отображаются как вложение без названия и расширения, что неудобно.
http://joxi.ru/D2PeQVZHzRdLA3
Можно сделать их просто текстом  в письме?
А то с Питоном совсем не дружу :(

**Comment by v00g100skr** [comment]
думаю да. погляжу в течение недели, как будет время

**Comment by martrix78** [comment]
Спасибо :)
Хороший парсер, по функционалу и удобству настройки все супер. Единственное я бы добавил в readme инструкцию где взять usess  - а то долго его искал среди 15 кукисов :)

**Comment by v00g100skr** [comment]
добавлю

**Comment by v00g100skr** [comment]
пробуйте

**Comment by martrix78** [comment]
Получаю ошибку:

```
Traceback (most recent call last):
  File "parser.py", line 176, in <module>
    main()
  File "parser.py", line 139, in main
    status = send_email(config, email_torrents)
  File "parser.py", line 154, in send_email
    msg = MIMEText(text, "plain")
  File "/usr/lib/python2.7/email/mime/text.py", line 30, in __init__
    self.set_payload(_text, _charset)
  File "/usr/lib/python2.7/email/message.py", line 226, in set_payload
    self.set_charset(charset)
  File "/usr/lib/python2.7/email/message.py", line 262, in set_charset
    self._payload = self._payload.encode(charset.output_charset)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
```

какого то модуля не хватает?

**Comment by v00g100skr** [comment]
кириллицу в тексте не учел....
вечером поправлю

**Comment by martrix78** [comment]
не получилось?

**Comment by v00g100skr** [comment]
получилось. пробуйте

**Comment by martrix78** [comment]
класс, то что надо!
Спасибо :)
