### ISSUE TITLE
LostFilm change his engine and script stop working

### ISSUE THREAD

**Issue by CorwinRU** [utmcrow/lostfilm-rss-parser#3]
Hi!
First of all - thanks a lot for this great script, it's wery handful!
Unfortunately lostfilm website had a new design and something changed inside it. Therefore the script is failed to download torrents. Could you please fix this?

I've changed feed value in config.yml to http://old.lostfilm.tv/rssdd.xml. Torrent files is start to download, but transmission said that "This file is not a torrent file"

When I changing feed value in config.yml to http://www.lostfilm.tv/rss.xml the script I've got an error
`Traceback (most recent call last):
  File "parser.py", line 176, in <module>
    main()
  File "parser.py", line 77, in main
    torrent_filename = entry.link.split("&")[1]
IndexError: list index out of range`

**Comment by v00g100skr** [comment]
yep, I know about this
problem is in http://old.lostfilm.tv/rssdd.xml
this feed have links to http://lostfilm.tv
if manually remap links to old.lostfilm.tv - all works
i fix this soon

**Comment by v00g100skr** [comment]
http://www.lostfilm.tv/rss.xml dont have torrent links :-(

**Comment by CorwinRU** [comment]
Thanks for quick answer!
I'm afraid I'll have a minor knowledge of python and can't do on-the-fly remap in your code by myself
So… patiently waiting for a fix :-)

**Comment by v00g100skr** [comment]
I hope I find some time till the end of this week to fix this
but its will be a temporary solution
i think that lostfilm will remove soon old version of site and old rss feed

**Comment by i3laze** [comment]
А это политика GitHub всё на английском обсуждать?))

Thanks to **utmcrow** for a great script for my Linux XBMC box!

In case you're interested - there's a [workaround posted](http://old.lostfilm.tv/phpbb2.php?page=viewtopic&t=20921) in LostFilm.tv forum.
The idea is to rewrite a received torrent link URL:
$get = file_get_contents('http://old.lostftv/rssdd.xml');
$get = str_replace("https://www.lostfilm.tv/download.php", "http://old.lostfilm.tv/download.php", $get); 

I did this successfully. Just modify:
1. config.yml:    feed: `http://old.lostfilm.tv/rssdd.xml`
2. parser.py:     line 102: replace `entry.link,` with 
`entry.link.replace("www.lostfilm.tv/download.php", "old.lostfilm.tv/download.php"),`

It's just a workaround redirecting to an old site, which will be dropped someday.
Awaiting an updated parser for a new site.

**Comment by v00g100skr** [comment]
yep, I did this temporary hack and start working for a new parcel version
CorwinRU - try it

нет, это не политика гитхаба, я просто отвечаю на языке спросившего)))

**Comment by CorwinRU** [comment]
Still not working :-(
The script is successfully downloading file with .torrent extension, [except  it's not a torrent but html](https://dl.dropbox.com/s/6vb5q5y6vtxmsfw/1._Default_bash_2017-02-06_11-51-05.png?dl=0)


А про английский язык - это не политика гитхаба, я просто пишу на том языке, на котором readme опубликовано. Плюс еще - англоязычные товарищи смогут это прочесть, вдруг оно им поможет :-)

**Comment by CorwinRU** [comment]
in parser.py line 102
`entry.link.replace("www.lostfilm.tv/download.php", "old.lostfilm.tv/download.php")`
I've changed it to
`entry.link=entry.link.replace("www.lostfilm.tv/download.php", "old.lostfilm.tv/download.php")`

then script start working correctly

**Comment by v00g100skr** [comment]
super)
fixed

**Comment by i3laze** [comment]
> Здравствуйте!

> Приносим извинения за неудобства. Для автоматической загрузки файлов необходимо настроить торрент-клиент на ленту RSS сайта retre.org. 

> В настройке RSS-загрузчика в строку URL ленты необходимо ввести адрес вот в таком виде: http://retre.org/rssdd.xml:COOKIE:uid=xxxxxx; usess=xxxxxxxxxxxxxxxxxx, где uid – Ваш ID на сайте www.lostfilm.tv (указан в настройках в личном кабинете), а usess – юзер-сессия (указана в окне retre.org, внизу слева от значка RSS, по клику на надпись usess – будет показан Ваш usess).

**http://retre.org/rssdd.xml**
Сама лента работает как раньше, но в ссылках после id исчез параметр torrent_filename и чем его заменить - хз. Раньше они были:
https://www.lostfilm.tv/download.php?id=21544 &The.Expanse.S02E04.1080p.rus.LostFilm.TV.mkv.torrent
Теперь они вида:
http://tracktor.in/rssdownloader.php?id=21544

Поэтому сделаем Франкенштейна (возьмём torrent_filename из old RSS) и работаем дальше!
config.yml:
`feed: http://old.lostfilm.tv/rssdd.xml`
parser.py, line 102:
`entry.link.replace("https://www.lostfilm.tv/download.php", "http://tracktor.in/rssdownloader.php"), `
